print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rater you 'not'.")
print('I "said" do not touch this.')
print("I love python.")
#print("this is not run.")